/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../LIB/STD_TYPES.h"
#include "../LIB/BIT_MATH.h"
#include "../Inc/GPIO_interface.h"
#include "../Inc/RCC_interface.h"


int main(void)
{
/* Blink Led
	MRCC_voidInit();
	MRCC_u8EnableClk(RCC_APB2, RCC_APB2ENR_IOPD, ENABLE);
	MRCC_u8EnableClk(RCC_APB2, RCC_APB2ENR_IOPA, ENABLE);

	MGPIO_u8SetPinMode(GPIO_PORTA, GPIO_PIN0, GPIO_OUT_PUSH_PULL_2MHz);

	u16 i;
	for(;;)
	{
		MGPIO_u8SetPinValue(GPIO_PORTA, GPIO_PIN0, GPIO_PIN_HIGH);
		for(i=0;i<55000;i++);
		MGPIO_u8SetPinValue(GPIO_PORTA, GPIO_PIN0, GPIO_PIN_LOW);
		for(i=0;i<55000;i++);

	}
*/
	/* Led And switch
	MRCC_voidInit();
	//MRCC_u8EnableClk(RCC_APB2, RCC_APB2ENR_IOPD, ENABLE);
	MRCC_u8EnableClk(RCC_APB2, RCC_APB2ENR_IOPA, ENABLE);

	MGPIO_u8SetPinMode(GPIO_PORTA, GPIO_PIN1, GPIO_IN_PULL_DOWN);

	MGPIO_u8SetPinValue(GPIO_PORTA, GPIO_PIN1, GPIO_PIN_LOW);

	MGPIO_u8SetPinMode(GPIO_PORTA, GPIO_PIN0, GPIO_OUT_PUSH_PULL_2MHz);

	u8 state = 0;
	u16 i;
	for(;;)
	{
		MGPIO_u8GetPinValue(GPIO_PORTA, GPIO_PIN1, &state);
		if(state == 1)
		{
			MGPIO_u8WritePinAccess(GPIO_PORTA, GPIO_PIN0, GPIO_PIN_HIGH);
			for(i=0;i<55000;i++);
			MGPIO_u8WritePinAccess(GPIO_PORTA, GPIO_PIN0, GPIO_PIN_LOW);
			for(i=0;i<55000;i++);
		}
	}

*/
	/*
	MRCC_voidInit();
	//MRCC_u8EnableClk(RCC_APB2, RCC_APB2ENR_IOPD, ENABLE);
	MRCC_u8EnableClk(RCC_APB2, RCC_APB2ENR_IOPB, ENABLE);
	MGPIO_u8SetPortMode4_Pin(GPIO_PORTB, GPIO_HIGH_BYTE_UP_Nibble, GPIO_OUT_PUSH_PULL_2MHz);
	u16 i;
	for(;;)
	{
		MGPIO_u8SetPortValue4_Pin(GPIO_PORTB, GPIO_HIGH_BYTE_UP_Nibble, 0xf);
		for(i=0;i<55000;i++);
		MGPIO_u8SetPortValue4_Pin(GPIO_PORTB, GPIO_HIGH_BYTE_UP_Nibble, 0x0);
		for(i=0;i<55000;i++);
	}
	*/
	for(;;);
}

